// Classic 2008-era raster icons (see /public/icons, generated by scripts/gen-icons.mjs).
// Replaces emoji throughout the app with period-correct toolbar-style PNG icons.

// Icon names that exist as /public/icons/<name>.png
export type IconName =
  | 'work' | 'study' | 'personal' | 'exercise' | 'creative' | 'admin'
  | 'default' | 'beast' | 'balanced' | 'chill'
  | 'freelancer' | 'other' | 'warning' | 'check'
  | 'chart' | 'tasks'

// Map a category (by id or name) to a classic icon.
const CATEGORY_ICON: Record<string, IconName> = {
  work: 'work',
  job: 'work',
  professional: 'work',
  study: 'study',
  student: 'study',
  school: 'study',
  learning: 'study',
  personal: 'personal',
  home: 'personal',
  house: 'personal',
  family: 'personal',
  exercise: 'exercise',
  fitness: 'exercise',
  health: 'exercise',
  sport: 'exercise',
  creative: 'creative',
  art: 'creative',
  design: 'creative',
  admin: 'admin',
  administrative: 'admin',
  chores: 'admin',
  errand: 'admin',
  errands: 'admin',
}

const ALL_ICON_NAMES = new Set<string>([
  'work', 'study', 'personal', 'exercise', 'creative', 'admin',
  'default', 'beast', 'balanced', 'chill', 'freelancer', 'other', 'warning', 'check',
  'chart', 'tasks',
])

export function categoryIconName(cat?: { id?: string; name?: string; emoji?: string } | null): IconName {
  if (!cat) return 'default'
  // Custom categories store their chosen icon name in the `emoji` field.
  if (cat.emoji && ALL_ICON_NAMES.has(cat.emoji)) return cat.emoji as IconName
  const id = (cat.id || '').toLowerCase()
  const name = (cat.name || '').toLowerCase()
  if (CATEGORY_ICON[id]) return CATEGORY_ICON[id]
  if (CATEGORY_ICON[name]) return CATEGORY_ICON[name]
  // keyword fallback (e.g. "Work projects" -> work)
  for (const key of Object.keys(CATEGORY_ICON)) {
    if (name.includes(key)) return CATEGORY_ICON[key]
  }
  return 'default'
}

// All selectable icons for the category editor (custom categories can pick one).
export const PICKABLE_ICONS: IconName[] = [
  'work', 'study', 'personal', 'exercise', 'creative', 'admin',
  'beast', 'balanced', 'chill', 'freelancer', 'other', 'default',
]

export function ClassicIcon({
  name,
  size = 18,
  alt = '',
  className = '',
  style,
}: {
  name: IconName | string
  size?: number
  alt?: string
  className?: string
  style?: React.CSSProperties
}) {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={`/icons/${name}.png`}
      width={size}
      height={size}
      alt={alt}
      className={`classic-icon ${className}`}
      style={{ width: size, height: size, ...style }}
    />
  )
}
